# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test all Data Structures

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  run-pyetests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python packages
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install python packages
        run: |
          cd python_problems
          pip install -r requirements.txt
          cd tests
          pytest



